# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a3088aff289c335bacb29c20b58b85f"
name = "see-before-buy-ai-full"
application_url = "https://seebeforebuy.in"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[webhooks.privacy_compliance]
customer_deletion_url = "https://seebeforebuy.in/webhooks/customers/redact"
customer_data_request_url = "https://seebeforebuy.in/webhooks/customers/data_request"
shop_deletion_url = "https://seebeforebuy.in/webhooks/shop/redact"

[access_scopes]
scopes = "write_products,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ 
  "https://seebeforebuy.in/auth/callback",
  "https://seebeforebuy.in/auth/callback/",
  "https://seebeforebuy.in/auth",
  "https://seebeforebuy.in/api/auth",
  "https://seebeforebuy.in/api/auth/callback"
]
